# Generated by Django 3.1.2 on 2023-03-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('type_enquiry', models.IntegerField(choices=[(1, 'Consulta'), (2, 'Reclamo'), (2, 'Sugerencia'), (2, 'Felicitaciones')])),
                ('message', models.TextField()),
                ('notice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('is_new', models.BooleanField()),
                ('fabrication_date', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.brand')),
            ],
        ),
    ]
