# Generated by Django 3.1.2 on 2022-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211227_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
